using System.Collections.Generic;
using System.Linq;

namespace Gui.models
{
    internal class ConfigSchema
    {
        public List<string> CustomsReshalaBoss;
        public List<string> CustomsGoonsquadBoss;
        public List<string> CustomsCultistBoss;
        public List<string> DayFactoryTagillaBoss;
        public List<string> NightFactoryTagillaBoss;
        public List<string> NightFactoryCultistBoss;
        public List<string> InterchangeKillaBoss;
        public List<string> LighthouseZryachiyBoss;
        public List<string> LighthouseGoonsquadBoss;
        public List<string> ReserveGlukharBoss;
        public List<string> ShorelineSanitarBoss;
        public List<string> ShorelineGoonsquadBoss;
        public List<string> ShorelineCultistBoss;
        public List<string> StreetsKabanBoss;
        public List<string> StreetsKillaBoss;
        public List<string> WoodsShturmanBoss;
        public List<string> WoodsGoonsquadBoss;
        public List<string> WoodsCultistBoss;
        public List<int> RaiderToPmc;
        public List<int> RogueToPmc;
        public List<int> ScavengerToPmc;
        public int FleaMarketAccessLevel;
        public int HeadHitpoints;
        public int ChestHitpoints;
        public int StomachHitpoints;
        public int LeftArmHitpoints;
        public int LeftLegHitpoints;
        public int RightArmHitpoints;
        public int RightLegHitpoints;
        public int PmcFriendlyChance;
        public int PmcBackpackMaxValue;
        public int PmcVestMaxValue;
        public int ScavengerModeCooldown;
        public int TimeToDeploy;
        public int UsecToBearRatio;
        public double CustomsAirdropChance;
        public double WoodsAirdropChance;
        public double LighthouseAirdropChance;
        public double ShorelineAirdropChance;
        public double StreetsAirdropChance;
        public double ReserveAirdropChance;
        public double InterchangeAirdropChance;
        public double BossHealthMultiplier;
        public double BossFollowerHealthMultiplier;
        public double ScavengerHealthMultiplier;
        public double SpecialBotHealthMultiplier;
        public double ExtractExperienceMultiplier;
        public double KilledExperienceMultiplier;
        public double HideoutConstructionTimeMultiplier;
        public double HideoutProductionTimeMultiplier;
        public bool AccessLabsWithoutCard;
        public bool AllowExitFromAnySide;
        public bool ConvertCooperationExits;
        public bool DisableCustomBotWaves;
        public bool DisableFleaMarket;
        public bool DisableFallDamage;
        public bool DisableScavengerMode;
        public bool DisableSkillFatigue;
        public bool DisableRunthroughs;
        public bool ExtendRaidTimerToHour;
        public bool ExtendKeyUsageLimit;
        public bool ForceAllExitsAvailable;
        public bool InstantHideoutConstruction;
        public bool InstantHideoutProduction;
        public bool PatchScavengerExits;
        public bool RemoveFoundInRaidQuestConditions;

        public ConfigSchema()
        {
            CustomsReshalaBoss = new List<string>() { "35", "4" };
            CustomsGoonsquadBoss = new List<string>() { "35" };
            CustomsCultistBoss = new List<string>() { "15", "4" };
            DayFactoryTagillaBoss = new List<string>() { "30" };
            NightFactoryTagillaBoss = new List<string>() { "23" };
            NightFactoryCultistBoss = new List<string>() { "10", "2" };
            InterchangeKillaBoss = new List<string>() { "30" };
            LighthouseZryachiyBoss = new List<string>() { "100", "2" };
            LighthouseGoonsquadBoss = new List<string>() { "35", "Zone_TreatmentContainers,Zone_Chalet" };
            ReserveGlukharBoss = new List<string>() { "35", "2", "2", "2" };
            ShorelineSanitarBoss = new List<string>() { "35", "2,3", "ZoneGreenHouses,ZoneSanatorium1,ZoneGreenHouses,ZoneSanatorium2,ZonePort" };
            ShorelineCultistBoss = new List<string>() { "12", "3" };
            StreetsKabanBoss = new List<string>() { "35", "6" };
            StreetsKillaBoss = new List<string>() { "5" };
            WoodsShturmanBoss = new List<string>() { "35", "2" };
            WoodsGoonsquadBoss = new List<string>() { "35" };
            WoodsCultistBoss = new List<string>() { "15", "4" };
            RaiderToPmc = new List<int>() { 0, 0 };
            RogueToPmc = new List<int>() { 0, 0 };
            ScavengerToPmc = new List<int>() { 0, 0 };
            FleaMarketAccessLevel = 15;
            HeadHitpoints = 35;
            ChestHitpoints = 85;
            StomachHitpoints = 70;
            LeftArmHitpoints = 60;
            LeftLegHitpoints = 65;
            RightArmHitpoints = 60;
            RightLegHitpoints = 65;
            PmcFriendlyChance = 0;
            PmcBackpackMaxValue = 150000;
            PmcVestMaxValue = 50000;
            ScavengerModeCooldown = 1200;
            TimeToDeploy = 20;
            UsecToBearRatio = 50;
            CustomsAirdropChance = 5.0;
            InterchangeAirdropChance = 5.0;
            LighthouseAirdropChance = 5.0;
            ReserveAirdropChance = 5.0;
            ShorelineAirdropChance = 5.0;
            StreetsAirdropChance = 5.0;
            WoodsAirdropChance = 5.0;
            BossHealthMultiplier = 1.0;
            BossFollowerHealthMultiplier = 1.0;
            ScavengerHealthMultiplier = 1.0;
            SpecialBotHealthMultiplier = 1.0;
            ExtractExperienceMultiplier = 1.0;
            KilledExperienceMultiplier = 1.0;
            HideoutConstructionTimeMultiplier = 1.0;
            HideoutProductionTimeMultiplier = 1.0;
            AccessLabsWithoutCard = false;
            AllowExitFromAnySide = false;
            ConvertCooperationExits = false;
            DisableCustomBotWaves = false;
            DisableFleaMarket = false;
            DisableFallDamage = false;
            DisableScavengerMode = false;
            DisableSkillFatigue = false;
            DisableRunthroughs = false;
            ExtendRaidTimerToHour = false;
            ExtendKeyUsageLimit = false;
            ForceAllExitsAvailable = false;
            InstantHideoutConstruction = false;
            InstantHideoutProduction = false;
            PatchScavengerExits = false;
            RemoveFoundInRaidQuestConditions = false;
        }
    }
}
