namespace Gui.models
{
    internal class ConfigSchema
    {
        string[] CustomsReshalaBoss { set; get; }
        string[] CustomsGoonsquadBoss;
        string[] CustomsCultistBoss;
        string[] DayFactoryTagillaBoss;
        string[] NightFactoryTagillaBoss;
        string[] NightFactoryCultistBoss;
        string[] InterchangeKillaBoss;
        string[] LighthouseZryachiyBoss;
        string[] LighthouseGoonsquadBoss;
        string[] ReserveGlukharBoss;
        string[] ShorelineSanitarBoss;
        string[] ShorelineGoonsquadBoss;
        string[] ShorelineCultistBoss;
        string[] StreetsKabanBoss;
        string[] StreetsKillaBoss;
        string[] WoodsShturmanBoss;
        string[] WoodsGoonsquadBoss;
        string[] WoodsCultistBoss;
        int[] RaiderToPmc;
        int[] RogueToPmc;
        int[] ScavengerToPmc;
        int FleaMarketAccessLevel;
        int HeadHitpoints;
        int ChestHitpoints;
        int LeftArmHitpoints;
        int LeftLegHitpoints;
        int RightArmHitpoints;
        int RightLegHitpoints;
        int PmcFriendlyChance;
        int PmcBackpackMaxValue;
        int PmcPocketMaxValue;
        int PmcVestMaxValue;
        int ScavengerModeCooldown;
        int StomachHitpoints;
        int TimeToDeploy;
        int UsecToBearRatio;
        float CustomsAirdropChance;
        float WoodsAirdropChance;
        float LighthouseAirdropChance;
        float ShorelineAirdropChance;
        float StreetsAirdropChance;
        float ReserveAirdropChance;
        float InterchangeAirdropChance;
        float BossHealthMultiplier;
        float BossFollowerHealthMultiplier;
        float ExtractExperienceMultiplier;
        float KilledExperienceMultiplier;
        float HideoutConstructionTimeMultiplier;
        float HideoutProductionTimeMultiplier;
        float ScavengerHealthMultiplier;
        float SpecialBotHealthMultiplier;
        bool AccessLabsWithoutCard;
        bool AllowExitFromAnySide;
        bool ConvertCooperationExits;
        bool DisableCustomBotWaves;
        bool DisableFleaMarket;
        bool DisableFallDamage;
        bool DisableScavengerMode;
        bool DisableSkillFatigue;
        bool DisableRunthroughs;
        bool ExtendRaidTimerToHour;
        bool ExtendKeyUsageLimit;
        bool ForceAllExitsAvailable;
        bool InstantHideoutConstruction;
        bool InstantShowoutProduction;
        bool PatchScavengerExits;
        bool RemoveFoundInRaidQuestConditions;
    }
}
